### PR TITLE
CCIBI-463 Trade Product Id Cutoff and Wrapping Below Expand/Collapse …

### PR DESCRIPTION
**Pull request by andrey-liventsev-ontarget**
…Icon

Add .white-space-nowrap className

### CODE REVIEW

**Comment by johnny-five** [comment]
I, @Dantiff, have checked:

### Style/Standards/Process

* [ ] If there is commented out code that should be deleted
* [ ] That the change implements what was requested in the [ticket](https://technekes.atlassian.net/browse/CCIBI-463)
* [ ] For adequate test coverage for changed lines or critical code paths

### Code Quality

* [ ] Do the classes follow [CodeClimate 7 Patterns to Refactor](http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/)
* [ ] If there are more idiomatic ways of using our frameworks/libraries
* [ ] Are there alternative implementations or refactors that increase readability/understandability and/or maintainability
* [ ] I can actually understand what the code is doing (if you're struggling to understand, then others may as well)
* [ ] This change is ready for production, if not should there should be a [feature flag](https://github.com/voormedia/flipflop)

### Security and Privacy

* [ ] Do the changes raise any security or privacy concerns

**Comment by ben-dalton** [comment]
@andrey-liventsev-ontarget Can you add a note in the story documentation explaining that this class is available, the behavior and where to add it in implementation?

**Comment by andrey-liventsev-ontarget** [comment]
@ben-dalton The Table component use a huge configuration described in several nested objects.
I can apply this className to the single column in the story just for example. Is it would be enough?
If not, could you give an example of such documentation?

**Comment by ben-dalton** [comment]
@andrey-liventsev-ontarget Let's add a markdown table with the utility classNames.
```
| className | Target | Behavior | default |
|-------------------------|--------|--------------------------------------|---------|
| whitespace-nowrap | cell | prevents line break in the cell | no |
| vertically-align-center | cell | vertically align center cell content | yes |
| vertically-align-end | cell | vertically align end cell content | no |
```

**Pull request merged**
