### PR TITLE
CCIBI-5429 Input text is invisible if selected using autofill

### PR DESCRIPTION
**Pull request by andrey-liventsev-ontarget**
Fix input styles to make input text visible

### CODE REVIEW

**Comment by johnny-five** [comment]
I, @cachapman, have checked:

### Style/Standards/Process

* [ ] If there is commented out code that should be deleted
* [ ] That the change implements what was requested in the [ticket](https://technekes.atlassian.net/browse/CCIBI-5429)
* [ ] For adequate test coverage for changed lines or critical code paths

### Code Quality

* [ ] Do the classes follow [CodeClimate 7 Patterns to Refactor](http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/)
* [ ] If there are more idiomatic ways of using our frameworks/libraries
* [ ] Are there alternative implementations or refactors that increase readability/understandability and/or maintainability
* [ ] I can actually understand what the code is doing (if you're struggling to understand, then others may as well)
* [ ] This change is ready for production, if not should there should be a [feature flag](https://github.com/voormedia/flipflop)

### Security and Privacy

* [ ] Do the changes raise any security or privacy concerns

**Comment by cachapman** [comment]
Since you added this a while ago in #722 , what did this do in the referenced PR?

**Comment by andrey-liventsev-ontarget** [comment]
> Since you added this a while ago in #722 , what did this do in the referenced PR?
@cachapman 
The corresponding issue is CCIBI-3739
I don't remember why I added those particular styles - it was a long time ago

**Comment by cachapman** [comment]
Hmm... looks like it could have just been a bug that slipped through. I'm ok with this update

**Review by cachapman — APPROVED** [review]

**Pull request merged**
